#!/bin/env sh

if test -e "$HOME"/.config/setup/firstboot-complete; then
  echo "Already ran"
  exit 0
fi

(
  echo "# Waiting for internet connection"
  until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
  echo "00"

  echo "# Removing filtered Flathub repository"
  /usr/bin/flatpak remote-delete --force flathub || :
  if "$?" != 0; then
    zenity --error --text="Failed to remove filtered Flathub repository"
    exit 1
  fi
  echo "3"

  echo "# Adding Flathub repository"
  /usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  if "$?" != 0; then
    zenity --error \
      --text="Failed to add Flathub repository"
    exit 1
  fi
  echo "5"

  echo "# Replacing Fedora Flatpaks with Flathub Flatpaks (this may take a while)"
  /usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
  /usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to replace Fedora Flatpaks with Flathub Flatpaks"
    exit 1
  fi
  echo "20"

  echo "# Removing Fedora Flatpak repository"
  /usr/bin/flatpak remote-delete fedora --force ||:
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to remove Fedora Flatpak repository"
    exit 1
  fi
  echo "25"

  echo "# Installing Firefox"
  /usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Firefox"
    exit 1
  fi
  echo "30"

  echo "# Installing Thunderbird"
  /usr/bin/flatpak install --user --noninteractive flathub org.mozilla.Thunderbird
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Thunderbird"
    exit 1
  fi
  echo "40"

  echo "# Installing Extension Manager"
  /usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Extension Manager"
    exit 1
  fi
  echo "50"

  echo "# Installing LibreOffice"
  /usr/bin/flatpak install --user --noninteractive flathub org.libreoffice.LibreOffice
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install LibreOffice"
    exit 1
  fi
  echo "70"

  echo "# Installing DejaDup Backup"
  /usr/bin/flatpak install --user --noninteractive flathub org.gnome.DejaDup
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install DejaDup Backup"
    exit 1
  fi
  echo "80"

  echo "# Installing Font Downloader"
  /usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Font Downloader"
    exit 1
  fi
  echo "85"

  echo "# Installing Flatseal"
  /usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Flatseal"
    exit 1
  fi
  echo "90"

  echo "# Installing Celluloid Media Player"
  /usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
  if [ "$?" != 0 ] ; then
    zenity --error \
      --text="Failed to install Celluloid Media Player"
    exit 1
  fi
  echo "100"

  echo "Finishing up..."
  mkdir -p "$HOME"/.config/setup
  touch "$HOME"/.config/setup/firstboot-complete

) | zenity --progress --title="Firstboot" --text="Running firstboot tasks" --auto-close --auto-kill --percentage=0 --no-cancel --width=400

if [ "$?" != 0 ] ; then
  zenity --error \
    --text="Firstboot Failed"
  exit 1
fi
