name: Build and Push Image

on:
  # To save on build minutes, this should currently be tested locally and triggered manually
  #  push:
  #    paths-ignore:
  #      - '.github/**'
  #    branches:
  #      - main
  #pull_request:
  #  paths-ignore:
  #    - '.github/**'
  schedule:
    # Every Monday at 00:00 while the repository is not used, or is in active development
    - cron: '0 0 * * 1'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  base-images:
    name: Build Base Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_major_version: [37]
        fedora_project: [silverblue, kinoite]
        include:
          - image_name: fedora-base
          - location: ./base
          # Create aliases for the latest and stable tags
          - fedora_major_version: 37
            is_latest: true
            is_stable: true
          - tags: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metadata
        id: generate-metadata
        shell: bash
        run: |
          echo "date=$(date +%Y%m%d)-${{ matrix.fedora_project }}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)-${{ matrix.fedora_project }}" >> $GITHUB_OUTPUT
          echo "release=${{ matrix.fedora_major_version }}-${{ matrix.fedora_project }}" >> $GITHUB_OUTPUT

          alias_tags=()
          if [[ "${{ matrix.is_latest }}" == "true" ]]; then
            alias_tags+=("latest-${{ matrix.fedora_project }}")
          fi
          if [[ "${{ matrix.is_stable }}" == "true" ]]; then
            alias_tags+=("stable-${{ matrix.fedora_project }}")
          fi
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image_name }}
          tags: |
            ${{ steps.generate-metadata.outputs.alias_tags }}
            ${{ steps.generate-metadata.outputs.release }}
            ${{ steps.generate-metadata.outputs.date }}
            ${{ steps.generate-metadata.outputs.sha_short }}
          context: ${{ matrix.location }}
          containerfiles: |
            ${{ matrix.location }}/Containerfile.${{ matrix.fedora_project }}
          build-args: |
            FEDORA_MAJOR_VERSION=${{ matrix.fedora_major_version }}
          oci: true

      # Workaround bug where capital letters in your GitHub user ame make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Set registry
        id: registry_case
        if: github.ref == 'refs/heads/main'
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push image to GHCR
        id: push
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
