name: Build and Push Image

on:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

env:
  IMAGE_TAGS: latest ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  base-images:
    name: Build Base Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - location: ./base
            image_name: base

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ env.IMAGE_TAGS }}
          context: ${{ matrix.location }}
          containerfiles: |
            ${{ matrix.location }}/Containerfile
          oci: true

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
