name: Run pre-commit hooks
on:
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Check for new or updated files
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "pre-commit changed files, please run pre-commit locally and commit the changes"
            exit 1
          fi
